services:
#    my_app_films.example:
#        class: MyApp\FilmsBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    app.locale_listener:
        class: MyApp\FilmsBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }